# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # 코드 스타일
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # 타입 안정성
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    
    # 코드 품질
    avoid_print: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    
    # 문서화
    public_member_api_docs: false
    
    # 정렬
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # 기타
    use_key_in_widget_constructors: true
    require_trailing_commas: true
